services:
  - type: web
    name: stock-sutra
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    rootDir: server
    buildFilter:
      paths:
        - server/**
        - client/build/**
    autoDeploy: true
